### ISSUE TITLE
When using cloudflare R2 hosting URLs incorrect

### ISSUE THREAD

**Issue by himynamesdave** [muchdogesec/obstracts#114]
See response from image endpoint has `https://https://`

```
{
  "page_size": 50,
  "page_number": 1,
  "page_results_count": 1,
  "total_results_count": 1,
  "images": [
    {
      "name": "0_image_0.png",
      "url": "https://https://pub-c76bbc9f936b4cd3929aadc9c2afc70a.r2.dev/84a8ff1c-c463-5a97-b0c4-93daf7102b5f/files/0_image_0.png"
    }
  ]
}
```

**Comment by fqrious** [comment]
it needs host name, not url... remove `https://` from the env. 
should be 
`R2_CUSTOM_DOMAIN=pub-c76bbc9f936b4cd3929aadc9c2afc70a.r2.dev` 

NOT 
`R2_CUSTOM_DOMAIN=https://pub-c76bbc9f936b4cd3929aadc9c2afc70a.r2.dev`
