### ISSUE TITLE
Remove OPEN AI MODEL from env var and add to new AI flags to profile

### ISSUE THREAD

**Issue by himynamesdave** [muchdogesec/obstracts#27]
To support this change, 

https://github.com/muchdogesec/txt2stix/issues/55

we should make

--ai_settings_extractions (is list)
--ai_settings_relationships

setting to create the profile

User must set if using AI relationship mode (`ai_settings_relationships`) or AI extraction mode (`ai_settings_extractions`)

We also need to add anthropic and gemini keys to the env file to support txt2stix change

**Comment by himynamesdave** [comment]
@fqrious need to update all schemas to include the new flags

![Image](https://github.com/user-attachments/assets/1eb81318-880d-4b95-b2a3-458151460648)

**Comment by fqrious** [comment]
you need to build, it's updated

![here](https://github.com/user-attachments/assets/15f6b34d-ac74-468f-bfa4-553d0b204885)
