### ISSUE TITLE
Remove stixify references in the code

### ISSUE THREAD

**Issue by himynamesdave** [muchdogesec/obstracts#53]
https://github.com/muchdogesec/obstracts/blob/impl/obstracts/cjob/obstracts_helpers.py

^^ just one example. Stixify appears in a few places

We need to make the code cleaner, for those reading it.

Having references to Stixify is confusing.

I appreciate we may be reusing components between products, which is fine.

However, we should name them neutrally for reader clearity.

**Comment by himynamesdave** [comment]
@fqrious i also think this is causing larger issues 

collections are now being created for stixify

![image](https://github.com/user-attachments/assets/1406784e-69b9-49d5-bc75-e876708ec920)

**Comment by fqrious** [comment]
I'm going to fix the issue here, but there's no need to change the class name as it makes sense since the purpose of the class is to stixify a post
