### ISSUE TITLE
POST feed response needs to be improved

### ISSUE THREAD

**Issue by himynamesdave** [muchdogesec/obstracts#55]
Currently it's confusing. Need to improve.

Currently returns;

```
{
  "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "feed_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "created": "2024-09-05T09:01:20.409Z",
  "state": "retrieving",
  "history4feed_status": "pending",
  "item_count": 2147483647,
  "processed_items": 2147483647,
  "failed_processes": 2147483647
}
```

(currently the id shows job id not feed id -- which is confusing)

Should be more like h4f

```
{
  "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "job_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "job_state": "string",
  "count_of_posts": 0,
  "title": "string",
  "description": "string",
  "url": "string",
  "earliest_item_pubdate": "2024-09-05T09:00:59.592Z",
  "latest_item_pubdate": "2024-09-05T09:00:59.592Z",
  "datetime_added": "2024-09-05T09:00:59.592Z",
  "feed_type": "string",
  "include_remote_blogs": true
}
```

**Comment by fqrious** [comment]
I did this on purpose, create post returns a Job not a Feed.

**Comment by himynamesdave** [comment]
ok, but it's not clear what is returned here.

The assumption is the id will represent the feed, at a minimum

I think it makes more sense to return the same as h4f

**Comment by fqrious** [comment]
we can just add that it returns a job in description, if you check the schema of the response it's already a job so it should stay like that. 

That's also kinda the standard for POST requests that trigger jobs, for example, if we look at the POST request for Taxii Server, it's like that too
