### ISSUE TITLE
`/api/v1/feeds/{feed_id}/posts/{post_id}/` should accept body

### ISSUE THREAD

**Issue by himynamesdave** [muchdogesec/obstracts#63]
Currently will just update post by grabbing latest remote copy.

User should a specify the profile_id they want to use. This allow users to reindex a blog post with different extractions applied. 

This is useful if new profiles are added they want to use.

**Comment by fqrious** [comment]
same as #62, we should probably remove patch body from feed for now as this infrastructure problem is not easily fixable

**Comment by himynamesdave** [comment]
Closing this, as should be possible in 

https://github.com/muchdogesec/history4feed/issues/33
