### ISSUE TITLE
Better handling of images extracted from html

### ISSUE THREAD

**Issue by himynamesdave** [muchdogesec/obstracts#72]
Currently file2txt will store a copy of the image on the filesystem, and this is then referenced in the markdown output.

This is problematic, as user does not always have access to the filesystem (e.g. if a remote webserver)

We should expose the files in the document via an API endpoint

```
/api/v1/feeds/{feed_id}/posts/{post_id}/images/
```

The response of this endpoint will list all the images linked to the post

```
{ 
  "images" [
    "1.jpg"
    ]
}
```

These can then be accessed as follows

```
HOST/api/v1/feeds/{feed_id}/posts/{post_id}/images/1.jpg
```

The markwdown should be rewritten to include the full URL to the image (e.g. HOST/api/v1/feeds/{feed_id}/posts/{post_id}/images/1.jpg)

**Comment by fqrious** [comment]
This won't work because markdown is being converted in another module. The images are actually stored on the same server as the .md file and the url is relative

**Comment by himynamesdave** [comment]
So the point here is, the user must be able to access the image (if they do not have access to the server).

If we don't want to rewrite the report to include the web wrapper, we should still allow users to access the images directly from the API.

**Comment by fqrious** [comment]
so I did this then I realized a fatal mistake with it, it's impossible for django to know what server it's on until a request is made. and because of this, we cannot just hardcode an image link into the markdown file (note, media files are not served by django)

**Comment by fqrious** [comment]
Yes, we can do that...

**Comment by himynamesdave** [comment]
@fqrious we should also do this for h4f.

**Comment by himynamesdave** [comment]
I have a question...


when I run 

```
python3 file2txt.py \
  --mode html_article \
  --file tests/files/html-real/unit42-Fighting-Ursa-Luring-Targets-With-Car-for-Sale.html \
  --output examples/unit42-Fighting-Ursa-Luring-Targets-With-Car-for-Sale \
  --defang true \
  --extract_text_from_image true
```

I get a copy of all images stored locally and they exist in the doc like so

```
![A screenshot of an HTML document code on a computer screen, displaying various script tags and a hyperlink with a detailed URL.The document includes standard HTML structure tags such as doctype, head, and body.](0_image_0.png)
```

However, using the test cases (one post is the same content as above) I get markdown that looks like

```
curl -X 'GET' \
  'http://127.0.0.1:8001/api/v1/feeds/2d6575b8-3d90-5479-bdfe-b980b753ec40/posts/df6cd9d5-8493-5908-a3a6-2ae9b38ecf28/markdown/' \
  -H 'accept: */*'
```

```
.Figure 1 below shows the HTML returned from the webhook.site URL. 



![](https://muchdogesec.github.io/images/2024-08-01/0_image_0.png)




 Figure 1\.HTML code used in the attack hosted on the Webhook.site service. 



 The HTML shown above 
```

Which means no images are returned via Post image endpoint you've implemented.

Can you explain why this happens?

**Comment by fqrious** [comment]
The image is not valid, so it's left as is

**Comment by himynamesdave** [comment]
@fqrious can you explain what you mean, not valid? The file2txt and obstracts input files above are the same, so I'm not sure why one is valid, but the other is not

**Comment by fqrious** [comment]
it's 404, just go to the link

**Comment by himynamesdave** [comment]
Doh! Sorry, you're right
