### ISSUE TITLE
All posts being stored in same ArangoDB collection

### ISSUE THREAD

**Issue by himynamesdave** [muchdogesec/obstracts#85]
I have 4 blogs indexed, but all the STIX objects are being stored in the collections created for the first blog imported

![image](https://github.com/user-attachments/assets/483d8554-5b87-4213-b00a-a0bebee2f01b)

**Comment by fqrious** [comment]
can't reproduce

**Comment by fqrious** [comment]
you probably still have old h4f blogs lingering after rebuilding obstracts

**Comment by himynamesdave** [comment]
@fqrious yep, my bad. think it was an old DB. Working now.
