### ISSUE TITLE
URL multi select filters broken

### ISSUE THREAD

**Issue by himynamesdave** [muchdogesec/obstracts#92]
```
curl -X 'GET' \
  'http://localhost:8001/api/v1/feeds/2d6575b8-3d90-5479-bdfe-b980b753ec40/posts/c6a5afcd-2341-5a57-b936-b9a67667f57e/objects/?include_txt2stix_notes=false&types=attack-pattern,autonomous-system,bank-account,bank-card,campaign,course-of-action,cryptocurrency-transaction,cryptocurrency-wallet,directory,domain-name,email-addr,extension-definition,file,identity,indicator,infrastructure,intrusion-set,ipv4-addr,ipv6-addr,location,mac-addr,malware,marking-definition,network-traffic,note,phone-number,relationship,report,threat-actor,tool,url,user-agent,weakness,windows-registry-key' \
  -H 'accept: application/json'
```

Should treat it as attack-pattern OR autonomous-system OR ...

yet returns no results.

Run without the url filter returns results.

**Comment by fqrious** [comment]
![Image](https://github.com/user-attachments/assets/e64ec25a-e1ce-45c8-9939-9ba3c521f783)
works for me, can't reproduce

**Comment by himynamesdave** [comment]
can you help me validate something and run this request via the swagger ui?

**Comment by fqrious** [comment]
![Image](https://github.com/user-attachments/assets/748b9c4d-d8b3-44dc-ae8e-71f7ce0458a6)

**Comment by himynamesdave** [comment]
Still happening, but going to leave this one open b/c #61 seemed to solve itself, so will retest later
